force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Invoice no</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/QuickBooks_Domain__c.field-meta.xml
<CustomField>
    <fullName>QuickBooks_Domain__c</fullName>
    <label>QuickBooks Domain</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Quickbooks_Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>Quickbooks_Invoice_Id__c</fullName>
    <label>Quickbooks Invoice Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/QuoteID__c.field-meta.xml
<CustomField>
    <fullName>QuoteID__c</fullName>
    <label>QuoteID</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not paid</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/updateInvoicesStatusBatchTest.cls
@isTest(seeAllData=false)
private class updateInvoicesStatusBatchTest {

  @isTest
    static void updateInvoicButtonApexMock()
    {
        
        //Creating the Test Data
        Account acc = new Account(name='TestInvoice');
        insert acc;
  
        opportunity opp = new opportunity();
        opp.Name = 'TestOpportunity';
        opp.CloseDate=date.today().addMonths(2);
        opp.StageName='IsWon';
        insert opp;
         
        Quote q = new Quote();
        q.Name = 'TestQuote';
        q.opportunityId = opp.id;
        insert q;
        
        
        list<Invoice__c > listInvoice = new list<Invoice__c >();
       
             Invoice__c TestInvoice = new Invoice__c(Quickbooks_Invoice_Id__c='1',QuickBooks_Domain__c='Quotes',Account_Name__c=acc.id,QuoteID__c=q.id,status__C='Not paid');
             listInvoice.add(TestInvoice);
        
            insert listInvoice;
        
        // Testing the Apex class and API
        System.Test.startTest();
                  System.Test.setMock(HttpCalloutMock.class, new updateInvoicesStatusBatchMock());
                  updateInvoicesStatusBatch obj = new updateInvoicesStatusBatch();
                  DataBase.executeBatch(obj); 
        System.Test.stopTest();

     }
    
   
        
 

}