force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>A-{0}</displayFormat>
        <label>Invoice no</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/QuickBooks_Domain__c.field-meta.xml
<CustomField>
    <fullName>QuickBooks_Domain__c</fullName>
    <label>QuickBooks Domain</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/invoiceTest.cls
@isTest
public class invoiceTest {
    
    @isTest static void test1(){
        Account acc=new Account(name='test1');
        insert acc;
        Contact newCustomer=new Contact(Display_Name__c='test',AccountId=acc.id,email='test@gmail.com',Lastname='Test',CheckBeforeInsert__c=true);
        insert newCustomer;
        Invoice__c newInvoice=new Invoice__c(Account_Name__c=newCustomer.id,QuickBooks_Domain__c='test');
        List<Invoice__c> testList=new list<Invoice__c>();
        testList.add(newInvoice);
        invoice.preventInsertion(testList);
        invoice.prevent_delete(testList);
        
    }
    @isTest static void test2(){
        Account acc=new Account(name='test1');
        insert acc;
        Contact newCustomer=new Contact(Display_Name__c='test',AccountId=acc.id,email='test@gmail.com',Lastname='Test',CheckBeforeInsert__c=true);
        insert newCustomer;
        Invoice__c newInvoice=new Invoice__c(Account_Name__c=newCustomer.id);
        List<Invoice__c> testList=new list<Invoice__c>();
        testList.add(newInvoice);
        invoice.preventInsertion(testList);
        
    }

}